#
# Copyright 2014 Freescale Semiconductor, Inc.
# Copyright 2015 TQ Systems GmbH
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ../../freescale/common/

obj-y += tqmls1012al.o
obj-$(CONFIG_MBLS1012AL) += tqmls1012al_mbls1012al.o
