#
# Copyright 2014 Freescale Semiconductor, Inc.
# Copyright 2015 TQ Systems GmbH
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += tqmls102xa.o \
	tqmls102xa_eeprom.o

obj-$(CONFIG_FSL_DCU_FB) += dcu.o
