#
# board/tqc/tqmarzg2m_aa-mbarzg2x/Makefile
#
# Copyright (C) 2019 Renesas Electronics Corporation
# Copyright (C) 2021 TQ-Systems GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

obj-y	:= ../tqmarzg2x/tqmarzg2x-mbarzg2x.o
