# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2024 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#

obj-y += tqma95xxsa.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
endif
