## SPDX-License-Identifier: GPL-2.0-or-later
##
## Copyright (c) 2018-2023 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
## D-82229 Seefeld, Germany.
## Author: Markus Niebel
##

obj-y += tqma8x.o
obj-$(CONFIG_TQMA8X_BB_MBA8X) += tqma8x-mba8x.o

obj-$(CONFIG_SPL_BUILD) += spl.o
