# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2018 TQ-Systems GmbH

# necessary to create built-in.o
obj- := __dummy__.o

obj-$(CONFIG_TQC_EEPROM) += tqc_eeprom.o
obj-$(CONFIG_LAYERSCAPE_NS_ACCESS)	+= ns_access.o
