#
# Copyright (C) 2016 - 2020, Markus Niebel <Markus.Niebel@tq-group.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

# necessary to create built-in.o
obj- := __dummy__.o

obj-$(CONFIG_TQC_EEPROM) += tqc_eeprom.o
obj-$(CONFIG_TQC_EMMC) += tqc_emmc.o
obj-$(CONFIG_TQC_SDMMC) += tqc_sdmmc.o
