# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2026 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#

obj-y += tqma95xxla.o
obj-$(CONFIG_TQMA95XXLA_BB_MBA95XXCA) += tqma95xxla-mba95xxca.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
endif
