# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2022 TQ-Systems GmbH <license@tq-group.com>, D-82229 Seefeld, Germany.
#

obj-y := tqma64xxl.o

ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_TQMA64XXL_BOARD_MBAX4XXL) += tqma64xxl_mbax4xxl.o
endif
