# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile
#
# Copyright (C) 2021 TQ-Systems GmbH
#
# Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/

obj-y  := tqma335x.o

obj-$(CONFIG_MBA335X) += tqma335x_mba335x.o
