# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2025 TQ-Systems GmbH <u-boot@ew.tq-group.com>, D-82229 Seefeld, Germany.
# Author: Matthias Schiffer

obj-y := tqma67xx.o

ifndef CONFIG_XPL_BUILD
obj-$(CONFIG_TQMA67XX_BOARD_MBA67XX) += tqma67xx_mba67xx.o
endif
