# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2016-2026 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#

obj-$(CONFIG_TQ_COMMON_BB) += tq_bb.o
obj-$(CONFIG_TQ_COMMON_EEPROM) += tq_eeprom.o
obj-$(CONFIG_TQ_COMMON_ENVLOC) += tq_envloc.o
obj-$(CONFIG_TQ_COMMON_SOM) += tq_som.o
obj-$(CONFIG_TQ_COMMON_SDMMC) += tq_sdmmc.o
obj-$(CONFIG_TQ_COMMON_SPI_NOR) += tq_spi_nor.o
obj-$(CONFIG_TQ_COMMON_VARD) += tq_som_features.o
