# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2021-2023 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel, Matthias Schiffer
#

obj-y  := tqma6ul.o

obj-$(CONFIG_MBA6UL) += tqma6ul_mba6ul.o
