## SPDX-License-Identifier: GPL-2.0-or-later
##
## Copyright 2018 - 2020 TQ-Systems GmbH
##

obj-y += tqma8xxs.o
obj-$(CONFIG_TQMA8XXS_BB_MB_SMARC_2) += tqma8xxs-mb-smarc-2.o

obj-$(CONFIG_SPL_BUILD) += spl.o
