## SPDX-License-Identifier: GPL-2.0-or-later
##
## Copyright (c) 2018-2023 TQ-Systems GmbH  <u-boot@ew.tq-group.com>,
## D-82229 Seefeld, Germany.
## Author: Markus Niebel
##

obj-y += tqma8xxs.o
obj-$(CONFIG_TQMA8XXS_BB_MB_SMARC_2) += tqma8xxs-mb-smarc-2.o

obj-$(CONFIG_SPL_BUILD) += spl.o
