#
# board/tqc/tqmarzg2h_c-mbarzg2x/Makefile
#
# Copyright (C) 2019 Renesas Electronics Corporation
# Copyright (C) 2020 TQ-Systems GmbH
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= tqmarzg2h_c-mbarzg2x.o
