#
# board/tqc/tqmarzg2m_e-mbarzg2x/Makefile
#
# Copyright (C) 2019 Renesas Electronics Corporation
# Copyright (C) 2020 TQ-Systems GmbH
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= tqmarzg2m_e-mbarzg2x.o
