# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2023 TQ-Systems GmbH <u-boot@tq-group.com>, D-82229 Seefeld, Germany.
# Author: Matthias Schiffer

obj-y := tqma62xx.o

ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_TQMA62XX_BOARD_MBA62XX) += tqma62xx_mba62xx.o
endif
