#
# board/hoperun/tqmarzg2x-mbarzg2x/Makefile
#
# Copyright (C) 2021 Renesas Electronics Corporation
# Copyright (c) 2023 TQ-Systems GmbH <u-boot@ew.tq-group.com>, D-82229 Seefeld, Germany.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

obj-y	:= tqmarzg2x-mbarzg2x.o ../../renesas/rcar-common/common.o ../../renesas/rzg-common/update_fdt.o
