/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * Copyright (c) 2026 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
 * D-82229 Seefeld, Germany.
 * Author: Markus Niebel
 */

#ifndef __TQMA91_93_DRAM__
#define __TQMA91_93_DRAM__

#include <asm/arch/ddr.h>
#include <linux/types.h>

/* DRAM size is 512M * TQMA93XXXA_RAM_SIZE_n */
enum tqma93xxxa_ram_size {
	TQMA93XXXA_RAM_SIZE_0G5 = 1,
	TQMA93XXXA_RAM_SIZE_1G,
	TQMA93XXXA_RAM_SIZE_1G5,
	TQMA93XXXA_RAM_SIZE_2G,
};

struct dram_info {
	struct dram_timing_info	*table;  /* from NXP RPA */
	phys_size_t		size;    /* size of RAM */
	char			variant; /* char to help user query */
};

/* macro missing in  global headers for preprocessor concatenation */
#if !defined(CONCAT)
#define CONCAT(a, b) CONCAT1(a, b)
#define CONCAT1(a, b) CONCAT2(a, b)
#define CONCAT2(a, b) a##b
#endif

#if IS_ENABLED(CONFIG_IMX9_DRAM_INLINE_ECC)
#define DRAM_TIMING_NAME(NAME) CONCAT(NAME, _ecc)
#else
#define DRAM_TIMING_NAME(NAME) CONCAT(NAME, _noecc)
#endif

#define	DRAM_INFO_ENTRY(NAME, SIZE, VARIANT)  \
	{						\
		.table = &DRAM_TIMING_NAME(NAME),	\
		.size = (SIZE) * ULL(SZ_512M),		\
		.variant = VARIANT,			\
	}

/*
 * DDR timing / configuration generated with NXP DDR Tool
 * when adding new variants follow these naming conventions:
 * tqma9[1,3]xx[c,l]a_dram_timing_<size>_[noecc,ecc]
 * when renaming the autogenerated name of dram_timing_info
 * struct.
 */
#if IS_ENABLED(CONFIG_IMX93)
extern struct dram_timing_info DRAM_TIMING_NAME(tqma93xxca_dram_timing_1gb);
extern struct dram_timing_info DRAM_TIMING_NAME(tqma93xxla_dram_timing_1gb);
extern struct dram_timing_info DRAM_TIMING_NAME(tqma93xxla_dram_timing_1gb5);
extern struct dram_timing_info DRAM_TIMING_NAME(tqma93xxca_dram_timing_2gb);
extern struct dram_timing_info DRAM_TIMING_NAME(tqma93xxla_dram_timing_2gb);
#elif IS_ENABLED(CONFIG_IMX91)
extern struct dram_timing_info DRAM_TIMING_NAME(tqma91xxca_dram_timing_1gb);
extern struct dram_timing_info DRAM_TIMING_NAME(tqma91xxla_dram_timing_1gb);
#endif

extern struct dram_cfg_param ddr_ddrphy_trained_csr[];
extern const u32 ddr_ddrphy_trained_csr_num;

#endif
