# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2020-2023 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Gregor Herburger
#

obj-y += tqmlx2160a.o
obj-$(CONFIG_MBLX2160A) += tqmlx2160a_mblx2160a.o
obj-y += ddr.o
