## SPDX-License-Identifier: GPL-2.0-or-later
##
## Copyright (c) 2018-2023 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
## D-82229 Seefeld, Germany.
## Author: Markus Niebel
##

obj-y += tqma8xx.o
obj-$(CONFIG_TQMA8XX_BB_MBA8XX) += tqma8xx-mba8xx.o

obj-$(CONFIG_SPL_BUILD) += spl.o
