/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * K3: AM64 SoC definitions, structures etc.
 *
 * (C) Copyright (C) 2020-2021 Texas Instruments Incorporated - https://www.ti.com/
 */
#ifndef __ASM_ARCH_AM64_HARDWARE_H
#define __ASM_ARCH_AM64_HARDWARE_H

#include <config.h>
#ifndef __ASSEMBLY__
#include <linux/bitops.h>
#endif

#define PADCFG_MMR1_BASE				0x000f0000
#define MCU_PADCFG_MMR1_BASE				0x04080000
#define WKUP_CTRL_MMR0_BASE				0x43000000
#define MCU_CTRL_MMR0_BASE				0x04500000
#define CTRL_MMR0_BASE					0x43000000

#define CTRLMMR_WKUP_JTAG_DEVICE_ID			(WKUP_CTRL_MMR0_BASE + 0x18)
#define JTAG_DEV_ID_MASK				GENMASK(31, 18)
#define JTAG_DEV_ID_SHIFT				18
#define JTAG_DEV_CORE_NR_MASK				GENMASK(23, 22)
#define JTAG_DEV_CORE_NR_SHIFT				22
#define JTAG_DEV_R5_ADC_MASK				GENMASK(19, 18)
#define JTAG_DEV_R5_ADC_SHIFT				18
#define JTAG_DEV_FEATURES_MASK				GENMASK(17, 13)
#define JTAG_DEV_FEATURES_SHIFT				13
#define JTAG_DEV_SECURITY_MASK				BIT(12)
#define JTAG_DEV_SECURITY_SHIFT				12
#define JTAG_DEV_SAFETY_MASK				BIT(11)
#define JTAG_DEV_SAFETY_SHIFT				11
#define JTAG_DEV_SPEED_MASK				GENMASK(10, 6)
#define JTAG_DEV_SPEED_SHIFT				6
#define JTAG_DEV_TEMP_MASK				GENMASK(5, 3)
#define JTAG_DEV_TEMP_SHIFT				3
#define JTAG_DEV_PKG_MASK				GENMASK(2, 0)
#define JTAG_DEV_PKG_SHIFT				0

#define JTAG_DEV_ID_AM6442				0xca3
#define JTAG_DEV_ID_AM6441				0xc93
#define JTAG_DEV_ID_AM6422				0xca1
#define JTAG_DEV_ID_AM6421				0xc91
#define JTAG_DEV_ID_AM6412				0xca0
#define JTAG_DEV_ID_AM6411				0xc90

#define JTAG_DEV_FEATURES_C				0x3
#define JTAG_DEV_FEATURES_D				0x4
#define JTAG_DEV_FEATURES_E				0x5
#define JTAG_DEV_FEATURES_F				0x6

#define CTRLMMR_WKUP_DEVICE_FEATURE0			(WKUP_CTRL_MMR0_BASE + 0x60)
#define CTRLMMR_WKUP_DEVICE_FEATURE2			(WKUP_CTRL_MMR0_BASE + 0x68)
#define CTRLMMR_WKUP_DEVICE_FEATURE6			(WKUP_CTRL_MMR0_BASE + 0x78)

#define DEVICE_FEATURE0_R5FSS1_CORE_MASK		GENMASK(19, 18)
#define DEVICE_FEATURE0_R5FSS1_CORE_SHIFT		18
#define DEVICE_FEATURE0_R5FSS0_CORE_MASK		GENMASK(17, 16)
#define DEVICE_FEATURE0_R5FSS0_CORE_SHIFT		16
#define DEVICE_FEATURE0_MPU_CORE_MASK			GENMASK(1, 0)
#define DEVICE_FEATURE0_MPU_CORE_SHIFT			0

#define CTRLMMR_MAIN_DEVSTAT				(CTRL_MMR0_BASE + 0x30)

#define MAIN_DEVSTAT_PRIMARY_BOOTMODE_MASK		0x00000078
#define MAIN_DEVSTAT_PRIMARY_BOOTMODE_SHIFT		3

#define MAIN_DEVSTAT_PRIMARY_BOOTMODE_CFG_MASK		0x00000380
#define MAIN_DEVSTAT_PRIMARY_BOOTMODE_CFG_SHIFT		7

#define MAIN_DEVSTAT_BACKUP_BOOTMODE_MASK		0x00001c00
#define MAIN_DEVSTAT_BACKUP_BOOTMODE_SHIFT		10

#define MAIN_DEVSTAT_BACKUP_BOOTMODE_CFG_MASK		0x00002000
#define MAIN_DEVSTAT_BACKUP_BOOTMODE_CFG_SHIFT		13

/* After the cfg mask and shifts have been applied */
#define MAIN_DEVSTAT_PRIMARY_MMC_PORT_SHIFT		2
#define MAIN_DEVSTAT_PRIMARY_MMC_PORT_MASK		0x04
#define MAIN_DEVSTAT_PRIMARY_MMC_FS_RAW_SHIFT		0
#define MAIN_DEVSTAT_PRIMARY_MMC_FS_RAW_MASK		0x01

#define MAIN_DEVSTAT_PRIMARY_USB_MODE_SHIFT		1
#define MAIN_DEVSTAT_PRIMARY_USB_MODE_MASK		0x02

#define MAIN_DEVSTAT_BACKUP_USB_MODE_MASK		0x01

#define ROM_EXTENDED_BOOT_DATA_INFO			0x701beb00

/* Use Last 2K as Scratch pad */
#define TI_SRAM_SCRATCH_BOARD_EEPROM_START		0x7019f800

/* Reset Reason Detection */
#define CTRLMMR_MCU_RST_SRC			(MCU_CTRL_MMR0_BASE + 0x18178)

/* Reset causes by bit mapping */
#define RST_SRC_SAFETY_ERR			BIT(31)
#define RST_SRC_MAIN_ESM_ERR			BIT(30)
#define RST_SRC_SW_MAIN_POR_FROM_MAIN		BIT(25)
#define RST_SRC_SW_MAIN_POR_FROM_MCU		BIT(24)
#define RST_SRC_SW_MAIN_WARM_FROM_MAIN		BIT(21)
#define RST_SRC_SW_MAIN_WARM_FROM_MCU		BIT(20)
#define RST_SRC_SW_MCU_WARM_RST			BIT(16)
#define RST_SRC_SMS_WARM_RST			BIT(13)
#define RST_SRC_SMS_COLD_RST			BIT(12)
#define RST_SRC_DEBUG_RST			BIT(8)
#define RST_SRC_THERMAL_RST			BIT(4)
#define RST_SRC_MAIN_RESET_PIN			BIT(2)
#define RST_SRC_MCU_RESET_PIN			BIT(0)

static inline int k3_get_core_nr(void)
{
	u32 full_devid = readl(CTRLMMR_WKUP_JTAG_DEVICE_ID);

	return (full_devid & JTAG_DEV_CORE_NR_MASK) >> JTAG_DEV_CORE_NR_SHIFT;
}

static inline u32 k3_get_cores_r5fss0(void)
{
	u32 feature0 = readl(CTRLMMR_WKUP_DEVICE_FEATURE0);

	return (feature0 & DEVICE_FEATURE0_R5FSS0_CORE_MASK) >>
		DEVICE_FEATURE0_R5FSS0_CORE_SHIFT;
}

static inline u32 k3_get_cores_r5fss1(void)
{
	u32 feature0 = readl(CTRLMMR_WKUP_DEVICE_FEATURE0);

	return (feature0 & DEVICE_FEATURE0_R5FSS1_CORE_MASK) >>
		DEVICE_FEATURE0_R5FSS1_CORE_SHIFT;
}

static inline bool k3_has_adc(void)
{
	u32 full_devid = readl(CTRLMMR_WKUP_JTAG_DEVICE_ID);
	u32 devid = (full_devid & JTAG_DEV_ID_MASK) >> JTAG_DEV_ID_SHIFT;

	switch (devid) {
	case JTAG_DEV_ID_AM6442:
	case JTAG_DEV_ID_AM6441:
	case JTAG_DEV_ID_AM6422:
	case JTAG_DEV_ID_AM6421:
		return true;
	default:
		return false;
	}
}

static inline int k3_has_icss(void)
{
	u32 full_devid = readl(CTRLMMR_WKUP_JTAG_DEVICE_ID);
	u32 feature_code = (full_devid & JTAG_DEV_FEATURES_MASK) >>
			    JTAG_DEV_FEATURES_SHIFT;

	switch (feature_code) {
	case JTAG_DEV_FEATURES_D:
	case JTAG_DEV_FEATURES_E:
	case JTAG_DEV_FEATURES_F:
		return true;
	default:
		return false;
	}
}

#if defined(CONFIG_SYS_K3_SPL_ATF) && !defined(__ASSEMBLY__)

#define AM64X_DEV_RTI8			127
#define AM64X_DEV_RTI9			128

static const u32 put_device_ids[] = {
	AM64X_DEV_RTI9,
	AM64X_DEV_RTI8,
};

#endif

#define AM64X_DEV_R5FSS0_CORE0		121
#define AM64X_DEV_R5FSS0_CORE1		122

static const u32 put_core_ids[] = {
	AM64X_DEV_R5FSS0_CORE1,
	AM64X_DEV_R5FSS0_CORE0, /* Handle CPU0 after CPU1 */
};

#endif /* __ASM_ARCH_DRA8_HARDWARE_H */
