# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021, Renesas Electronics Corporation. All rights reserved.

obj-$(CONFIG_RZF_DDR_C_010_D3_02_2)	+= param_mc_C-010_D3-02-2.o
obj-$(CONFIG_RZF_DDR_C_010_D4_01_1)	+= param_mc_C-010_D4-01-1.o
obj-$(CONFIG_RZF_DDR_C_010_D4_01_2)	+= param_mc_C-010_D4-01-2.o
obj-$(CONFIG_RZF_DDR_C_011_D4_01_1)	+= param_mc_C-011_D4-01-1.o
obj-$(CONFIG_RZF_DDR_C_011_D4_01_2)	+= param_mc_C-011_D4-01-2.o
