# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2019-2022 TQ-Systems GmbH <u-boot@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Gregor Herburger
#

obj-y += tqmls1088a.o
obj-$(CONFIG_TQMLS1088A_BB_MBLS10XXA) += tqmls1088a_bb_mbls10xxa.o
