#
# Copyright 2018-2019 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += tqmls1028a.o ddr.o
obj-$(CONFIG_MBLS1028A) += tqmls1028a_mbls1028a.o
obj-$(CONFIG_MBLS1028A_IND) += tqmls1028a_mbls1028a.o
