# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2022-2025 TQ-Systems GmbH <u-boot@ew.tq-group.com>, D-82229 Seefeld, Germany.
# Author: Nora Schiffer

obj-y := tqma64xxl.o

ifndef CONFIG_XPL_BUILD
obj-$(CONFIG_TQMA64XXL_BOARD_MBAX4XXL) += tqma64xxl_mbax4xxl.o
endif
